/**
 * @author ssaleh
 *
 * Created date 12 Sep 2017
 */
package net.sh4m.project.enums;

public enum ActivityEnums {
	ADDPROJECT,
	UPDATEPROJECT,
	DELETEPROJECT,
	APPROVEPROJECT,
	UPDATEMAPPING,
	DUPLICATEMAPPING,
	DELETEMAPPING,
	ADDCOUNTRYCODE, 
	UPDATECOUNTRYCODE, 
	DELETECOUNTRYCODE,
	ADDELEMENT, 
	APPROVETEMPLATE, 
	UATGENERATEXML, 
	UPDATEMASTERLIB, 
	ADDSETTINGSMENU, 
	ADDGROUPMENUMAPPING, 
	DELGROUPMENUMAPPING, 
	UPDATEWORKFLOW, 
	GENCOMPAREXMLPDF, 
	PROJAPPROVALNOTIFICATION, 
	APPROVEPROJECTFORLIVE, 
	LIVEGENERATEXML, 
	LIVEGENERATEPDF, 
	UATGENERATEPDF
}
